waypoint_server:
  scale: 1
  position:
    x: 1
    y: 2
    z: 3
  euler_angles:
    x: 0
    y: 0
    z: 1.57
  waypoints:
    - id: registed_0_1724043355196943484
      position:
        x: 2.5439
        y: -70.52516
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_1724043342115144148
      position:
        x: 0.5153656
        y: -54.50896
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_1724043228230062165
      position:
        x: 0.5130653
        y: -22.05856
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_1722835408344918431
      position:
        x: 54.2923
        y: -28.30023
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
        - key: stop
          value: ""
    - id: registed_0_324770000000
      position:
        x: 20.05038
        y: 55.20764
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: goal_radius
          value: 2.000000
    - id: registed_0_1110507000000
      position:
        x: -2.152901
        y: 48.74594
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
    - id: registed_0_1102605000000
      position:
        x: 5.082733
        y: 49.9388
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: goal_radius
          value: 2.000000
    - id: registed_0_1722835197005063805
      position:
        x: 22.4836
        y: -124.3886
        z: -2.999998
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1722835250231555701
      position:
        x: 38.47777
        y: -128.7466
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
        - key: stop
          value: ""
    - id: registed_0_1722835073947641026
      position:
        x: 17.12764
        y: -107.8601
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: goal_radius
          value: 2.000000
    - id: registed_0_1724043377602292382
      position:
        x: 6.306572
        y: -87.81844
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_255629000000
      position:
        x: -4.744362
        y: 63.04114
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
    - id: registed_0_1724043272595734201
      position:
        x: 0.6422882
        y: -38.20078
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_1722835259500484836
      position:
        x: 47.20711
        y: -121.3607
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
        - key: stop
          value: ""
    - id: registed_0_1052707000000
      position:
        x: 20.23571
        y: 63.06734
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: false
        - key: goal_radius
          value: 0.5
    - id: registed_0_448334000000
      position:
        x: 15.83241
        y: 2.523634
        z: -3.000031
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 0.5
        - key: stop
          value: true
    - id: registed_0_1414823000000
      position:
        x: -4.239476
        y: -2.864141
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 1.583501
      properties:
        - key: goal_radius
          value: 2.000000
        - key: stop
          value: true
    - id: registed_0_1119405000000
      position:
        x: -5.145916
        y: 56.0731
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
    - id: registed_0_1652869641731469277
      position:
        x: 0.4747276
        y: -47.08858
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.556444
      properties:
        - key: area_select_ON
          value: ""
        - key: detect_box_ON
          value: ""
        - key: stop
          value: ""
        - key: goal_radius
          value: 2.000000
        - key: area_waypoint_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: area_select_OFF
          value: ""
        - key: white
          value: ""
        - key: standby_mode
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: detect_box_OFF
          value: ""
    - id: registed_0_1722835484874762445
      position:
        x: 46.94726
        y: -4.662056
        z: -3.000031
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1722835089223458443
      position:
        x: 25.73626
        y: -113.6889
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: goal_radius
          value: 2.000000
    - id: registed_0_1722835274780918029
      position:
        x: 53.92672
        y: -110.6037
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
        - key: stop
          value: ""
    - id: registed_0_1161583000000
      position:
        x: 10.11142
        y: 66.86652
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
    - id: registed_0_1722835391805910291
      position:
        x: 55.67685
        y: -44.29889
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
        - key: stop
          value: ""
    - id: registed_0_1065964000000
      position:
        x: 10.45845
        y: 53.23701
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: goal_radius
          value: 2.000000
    - id: registed_0_1711529268569425987
      position:
        x: 8.991936
        y: -98.06416
        z: -2.999997
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: goal_radius
          value: 2.000000
    - id: registed_0_1722835459543408051
      position:
        x: 49.57601
        y: -9.134605
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
        - key: stop
          value: ""
    - id: registed_0_1237017000000
      position:
        x: 11.37102
        y: 2.621448
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: false
        - key: goal_radius
          value: 0.5
    - id: registed_0_1186789000000
      position:
        x: 20.24086
        y: 60.62641
        z: -3
      euler_angles:
        x: -0
        y: 0
        z: 1.566316
      properties:
        - key: goal_radius
          value: 0.500000
        - key: stop
          value: false
    - id: registed_0_1652870290928670167
      position:
        x: 1.769569
        y: -62.54745
        z: -3.000003
      euler_angles:
        x: 0
        y: 0
        z: -1.559634
      properties:
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: stop
          value: ""
        - key: area_waypoint_OFF
          value: ""
        - key: goal_radius
          value: 2.000000
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: standby_mode
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
    - id: registed_0_1723102826251996552
      position:
        x: 11.33805
        y: 0.4185753
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 0.500000
    - id: registed_0_1722835426763931830
      position:
        x: 54.2634
        y: -14.74669
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
        - key: stop
          value: ""
    - id: registed_0_1722835302782943477
      position:
        x: 55.50816
        y: -69.44105
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
        - key: stop
          value: ""
    - id: registed_0_1134009000000
      position:
        x: -1.669754
        y: 71.55006
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
    - id: registed_0_1277517000000
      position:
        x: 15.92984
        y: 0.222681
        z: -3
      euler_angles:
        x: -0
        y: 0
        z: 1.569175
      properties:
        - key: stop
          value: ""
        - key: goal_radius
          value: 0.500000
    - id: registed_0_1722835502801754747
      position:
        x: 39.97684
        y: -4.682354
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_73158000000
      position:
        x: 0.64217
        y: -28.99978
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: area_select_ON
          value: ""
        - key: detect_box_ON
          value: ""
        - key: stop
          value: ""
        - key: goal_radius
          value: 2.000000
        - key: area_waypoint_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: area_select_OFF
          value: ""
        - key: white
          value: ""
        - key: standby_mode
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: detect_box_OFF
          value: ""
    - id: registed_0_1195264000000
      position:
        x: 20.17925
        y: 63.13702
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 0.5
        - key: stop
          value: true
    - id: registed_0_1722835694551141771
      position:
        x: 0.3802605
        y: -15.21629
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
        - key: stop
          value: ""
    - id: registed_0_1722835521288426846
      position:
        x: 31.63625
        y: -2.707542
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
        - key: stop
          value: ""
    - id: registed_0_1723102625066618600
      position:
        x: 20.27474
        y: 60.73291
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 0.500000
    - id: registed_0_428906000000
      position:
        x: 18.66138
        y: -2.872614
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -3.135126
      properties:
        - key: goal_radius
          value: 0.500000
        - key: stop
          value: true
    - id: registed_0_285467000000
      position:
        x: 20.32825
        y: 58.21481
        z: -2.999999
      euler_angles:
        x: -0
        y: -0
        z: 1.580236
      properties:
        - key: stop
          value: true
        - key: goal_radius
          value: 0.500000
    - id: registed_0_1722835529552540600
      position:
        x: 23.53043
        y: -2.938454
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
        - key: stop
          value: false
    - id: registed_0_1169690000000
      position:
        x: 12.49603
        y: 59.94028
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
    - id: registed_0_1378895000000
      position:
        x: -3.650678
        y: -7.74206
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
    - id: registed_0_1722835210197963815
      position:
        x: 28.40177
        y: -128.9886
        z: -3.000001
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 1.0
        - key: stop
          value: ""
    - id: registed_0_419033000000
      position:
        x: 11.07282
        y: -2.492604
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
    - id: registed_0_1722835471841594515
      position:
        x: 53.21441
        y: -5.573944
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -3.129473
      properties:
        - key: goal_radius
          value: 2.000000
        - key: stop
          value: ""
    - id: registed_0_1722835550513944635
      position:
        x: 10.98728
        y: -6.357545
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
        - key: stop
          value: ""
    - id: registed_0_1607116000000
      position:
        x: 2.760859
        y: -3.804509
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
    - id: registed_0_1722835334462447796
      position:
        x: 55.87442
        y: -57.55065
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
        - key: stop
          value: ""
    - id: registed_0_1722835183646609566
      position:
        x: 25.01562
        y: -119.5026
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: goal_radius
          value: 1.0
    - id: registed_0_1711527506559531697
      position:
        x: 4.597534
        y: -78.75929
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -1.544288
      properties:
        - key: stop
          value: false
        - key: goal_radius
          value: 2.000000
        - key: detect_box_ON
          value: ""
        - key: detect_box_OFF
          value: ""
    - id: registed_0_1722835288471762573
      position:
        x: 54.06053
        y: -90.42856
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
        - key: stop
          value: ""
    - id: registed_0_1150954000000
      position:
        x: 5.631721
        y: 71.6406
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
    - id: registed_0_1723102703417020520
      position:
        x: 16.25621
        y: 57.47521
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 2.000000
