waypoint_server:
  scale: 1
  position:
    x: 1
    y: 2
    z: 3
  euler_angles:
    x: 0
    y: 0
    z: 1.57
  waypoints:
    - id: registed_0_1652870290928670167
      position:
        x: 27.82302
        y: -2.121202
        z: -3
      euler_angles:
        x: -0
        y: 0
        z: 1.320233
    - id: registed_0_1652869641731469277
      position:
        x: -5.495299
        y: -1.590803
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -0.6118501
    - id: 3
      position:
        x: 28.11231
        y: 7.52545
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 3.13392
      properties:
        - key: stop
          value: true
      connections:
        - 1
    - id: registed_goal_0
      position:
        x: 10.67192
        y: 7.897385
        z: -3
      euler_angles:
        x: 8.742276e-08
        y: 1.509958e-07
        z: -3.137352
      properties:
        - key: stop
          value: true
        - key: goal_radius
          value: 1.0
    - id: registed_0_73158000000
      position:
        x: -5.413615
        y: 8.228432
        z: -2.999998
      euler_angles:
        x: 0
        y: 0
        z: -1.57
