waypoint_server:
  scale: 1
  position:
    x: 1
    y: 2
    z: 3
  euler_angles:
    x: 0
    y: 0
    z: 1.57
  waypoints:
    - id: registed_0_1706866441760787402
      position:
        x: -61.55539
        y: -84.27492
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: stop
          value: ""
        - key: standby_mode
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
    - id: registed_0_1654680342545707658
      position:
        x: -81.10397
        y: 23.68417
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: standby_mode
          value: ""
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
    - id: registed_0_1706866239283694682
      position:
        x: -136.2148
        y: 27.88909
        z: -3.000004
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: stop
          value: ""
        - key: standby_mode
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
    - id: registed_0_1710129373366322659
      position:
        x: -65.67869
        y: -113.8522
        z: -3.000002
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: area_waypoint_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: area_select_OFF
          value: ""
        - key: white
          value: ""
        - key: standby_mode
          value: ""
        - key: stop
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_ON
          value: ""
    - id: registed_0_1706866343072808411
      position:
        x: -80.66195
        y: 64.17024
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: true
    - id: registed_0_1654677673907365289
      position:
        x: -11.81554
        y: -53.35441
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: standby_mode
          value: ""
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
    - id: registed_0_1654679322742326305
      position:
        x: -51.67435
        y: -84.15038
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: standby_mode
          value: ""
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
    - id: registed_0_1710130113142738680
      position:
        x: -82.85003
        y: 2.953568
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_1706866477530057624
      position:
        x: -104.3208
        y: -19.55871
        z: -2.999992
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: stop
          value: ""
        - key: standby_mode
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
    - id: registed_0_1654677537510169550
      position:
        x: -104.0494
        y: -75.14246
        z: -3.000008
      euler_angles:
        x: 0
        y: 0
        z: -1.630845
      properties:
        - key: stop
          value: ""
        - key: standby_mode
          value: ""
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
    - id: 3
      position:
        x: -96.68327
        y: 45.61041
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.545381
      properties:
        - key: stop
          value: false
        - key: standby_mode
          value: ""
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
      connections:
        - 1
    - id: registed_0_1654680146185245363
      position:
        x: -63.02408
        y: -53.75954
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: standby_mode
          value: ""
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
    - id: registed_0_1654680413192867465
      position:
        x: -40.67853
        y: -4.427776
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1654679991160651057
      position:
        x: -136.0065
        y: -20.2917
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: standby_mode
          value: ""
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
    - id: registed_0_1707361813310850597
      position:
        x: -22.42011
        y: -150.2823
        z: -3.000001
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: stop
          value: ""
        - key: standby_mode
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
    - id: registed_0_1710062356131267768
      position:
        x: -16.51933
        y: -83.74619
        z: -2.999998
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: area_waypoint_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: area_select_OFF
          value: ""
        - key: white
          value: ""
        - key: standby_mode
          value: ""
        - key: stop
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_ON
          value: ""
    - id: registed_0_1654679339324142985
      position:
        x: -20.15228
        y: -83.97292
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: standby_mode
          value: ""
        - key: goal_radius
          value: 0.75
        - key: area_waypoint_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: area_select_OFF
          value: ""
        - key: white
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_ON
          value: ""
    - id: registed_0_1655896797021226582
      position:
        x: -73.28777
        y: -122.2754
        z: -2.999998
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: standby_mode
          value: ""
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
    - id: registed_0_1654680819130952632
      position:
        x: -81.39317
        y: 39.8655
        z: -3
      euler_angles:
        x: -0
        y: 0
        z: 1.522704
      properties:
        - key: goal_radius
          value: 0.75
        - key: stop
          value: true
    - id: registed_0_1654678354268406692
      position:
        x: -76.81572
        y: 45.88335
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 3.126895
      properties:
        - key: goal_radius
          value: 0.75
        - key: stop
          value: true
        - key: detect_box_ON
          value: ""
        - key: detect_box_OFF
          value: ""
    - id: registed_0_1654680378944707163
      position:
        x: -42.16969
        y: 24.34759
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1654680059267252585
      position:
        x: -78.18509
        y: -4.669487
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -0.2500968
      properties:
        - key: stop
          value: ""
        - key: standby_mode
          value: ""
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
    - id: registed_0_1654678923563628537
      position:
        x: -124.5942
        y: -114.1686
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: standby_mode
          value: ""
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
    - id: registed_0_1654679822231292893
      position:
        x: -131.3997
        y: -104.5189
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: standby_mode
          value: ""
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
    - id: registed_0_1654678829967410947
      position:
        x: -135.924
        y: 11.91682
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: standby_mode
          value: ""
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
    - id: registed_0_1654680680960191935
      position:
        x: -76.8945
        y: -4.72934
        z: -3
      euler_angles:
        x: 4.541778e-08
        y: 9.13226e-08
        z: 2.244247
      properties:
        - key: goal_radius
          value: 0.75
        - key: stop
          value: true
    - id: registed_0_1654679614858257698
      position:
        x: -66.67798
        y: -123.6066
        z: -3
      euler_angles:
        x: 4.869192e-08
        y: 2.024617e-08
        z: 1.737383
      properties:
        - key: stop
          value: true
        - key: detect_box_ON
          value: ""
        - key: detect_box_OFF
          value: ""
    - id: registed_0_1707058122226999661
      position:
        x: -28.82739
        y: -22.78853
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: detect_box_ON
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: stop
          value: ""
        - key: standby_mode
          value: ""
        - key: white
          value: ""
        - key: area_select_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: area_waypoint_OFF
          value: ""
