waypoint_server:
  scale: 1
  position:
    x: 1
    y: 2
    z: 3
  euler_angles:
    x: 0
    y: 0
    z: 1.57
  waypoints:
    - id: registed_0_1721362503587158292
      position:
        x: 28.49068
        y: 7.430517
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 0.75
        - key: stop
          value: true
    - id: registed_0_1706866239283694682
      position:
        x: 12.79345
        y: 7.897538
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 0.75
        - key: area_waypoint_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: area_select_OFF
          value: ""
        - key: white
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: standby_mode
          value: ""
        - key: stop
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_ON
          value: ""
    - id: registed_0_1710152634062124267
      position:
        x: -5.800232
        y: -1.539155
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 0.75
    - id: registed_0_1654679822231292893
      position:
        x: 12.70776
        y: -1.808833
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 0.75
        - key: area_waypoint_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: area_select_OFF
          value: ""
        - key: white
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_ON
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: standby_mode
          value: ""
        - key: stop
          value: ""
    - id: registed_0_1654678923563628537
      position:
        x: -5.841106
        y: 8.024347
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 0.75
        - key: area_waypoint_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: area_select_OFF
          value: ""
        - key: white
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_ON
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: standby_mode
          value: ""
        - key: stop
          value: ""
    - id: 3
      position:
        x: 26.97557
        y: 7.478302
        z: -3.000002
      euler_angles:
        x: 0
        y: 0
        z: -1.545381
      properties:
        - key: goal_radius
          value: 0.75
        - key: area_waypoint_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: area_select_OFF
          value: ""
        - key: white
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_ON
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: standby_mode
          value: ""
        - key: stop
          value: false
      connections:
        - 1
    - id: registed_0_1654679991160651057
      position:
        x: 27.7475
        y: -2.108583
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 0.75
        - key: area_waypoint_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: area_select_OFF
          value: ""
        - key: white
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_ON
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: standby_mode
          value: ""
        - key: stop
          value: ""
