waypoint_server:
  scale: 1
  position:
    x: 1
    y: 2
    z: 3
  euler_angles:
    x: 0
    y: 0
    z: 1.57
  waypoints:
    - id: registed_0_943866000000
      position:
        x: -26.03944
        y: 65.2282
        z: -2.999992
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_913507000000
      position:
        x: -48.89251
        y: 38.61016
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_897353000000
      position:
        x: -73.25333
        y: 12.54117
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_886918000000
      position:
        x: -80.03345
        y: 14.75293
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_877483000000
      position:
        x: -91.83265
        y: 22.65667
        z: -2.999992
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_927503000000
      position:
        x: -35.67015
        y: 55.97456
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_874191000000
      position:
        x: -102.2903
        y: 32.6274
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_859679000000
      position:
        x: -118.8943
        y: 51.66294
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_854169000000
      position:
        x: -125.3311
        y: 58.98683
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 0.5
    - id: registed_0_720881000000
      position:
        x: -164.412
        y: -57.42159
        z: -2.999992
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_711323000000
      position:
        x: -158.3104
        y: -63.32089
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_703116000000
      position:
        x: -138.2805
        y: -49.05847
        z: -3.000004
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_690516000000
      position:
        x: -127.9898
        y: -44.26163
        z: -3.000004
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_672719000000
      position:
        x: -113.7265
        y: -39.754
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 1.0
    - id: registed_0_635868000000
      position:
        x: -88.49615
        y: -40.45408
        z: -2.999992
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_767924000000
      position:
        x: -196.5209
        y: -1.700119
        z: -3.000004
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_642016000000
      position:
        x: -100.8811
        y: -50.19931
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_739539000000
      position:
        x: -179.8186
        y: -39.37704
        z: -2.999992
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_706473000000
      position:
        x: -148.6695
        y: -55.51001
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_919643000000
      position:
        x: -43.12973
        y: 47.81618
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_751415000000
      position:
        x: -195.5482
        y: -19.76871
        z: -3.000004
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_798420000000
      position:
        x: -165.1448
        y: 20.86082
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_775231000000
      position:
        x: -187.2999
        y: 2.201218
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_600053000000
      position:
        x: -66.92222
        y: -21.57841
        z: -2.999992
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_840456000000
      position:
        x: -136.2691
        y: 49.1604
        z: -2.999998
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_961584000000
      position:
        x: -11.68469
        y: 77.75095
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_908784000000
      position:
        x: -53.4162
        y: 29.12378
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_1650561188224170784
      position:
        x: -52.74074
        y: -8.877464
        z: -2.999998
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: area_waypoint_OFF
          value: ""
        - key: switch_segmentation_ON
          value: ""
        - key: traffic_sign_OFF
          value: ""
        - key: switch_segmentation_OFF
          value: ""
        - key: traffic_sign_ON
          value: ""
        - key: area_waypoint_ON
          value: ""
        - key: area_select_OFF
          value: ""
        - key: white
          value: ""
        - key: standby_mode
          value: ""
        - key: stop
          value: ""
        - key: detect_box_OFF
          value: ""
        - key: area_select_ON
          value: ""
        - key: detect_box_ON
          value: ""
    - id: registed_0_754867000000
      position:
        x: -203.6014
        y: -9.274902
        z: -3.000004
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_743670000000
      position:
        x: -187.0999
        y: -29.98657
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_863983000000
      position:
        x: -111.1374
        y: 42.91324
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_779006000000
      position:
        x: -180.8719
        y: 7.65538
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_827141000000
      position:
        x: -148.1299
        y: 34.41757
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_784575000000
      position:
        x: -175.8702
        y: 11.72629
        z: -2.999992
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_793782000000
      position:
        x: -170.4906
        y: 16.46292
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_821051000000
      position:
        x: -153.5296
        y: 29.86998
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_630163000000
      position:
        x: -78.8042
        y: -31.58557
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_809534000000
      position:
        x: -159.2032
        y: 24.76997
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_830009000000
      position:
        x: -142.5922
        y: 39.10512
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_833132000000
      position:
        x: -136.9503
        y: 43.87486
        z: -3.000002
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_900853000000
      position:
        x: -58.45291
        y: 24.14812
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_731136000000
      position:
        x: -171.4638
        y: -48.86545
        z: -2.999992
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_846456000000
      position:
        x: -128.8641
        y: 56.48439
        z: -3.000004
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 0.5
