TrajectoryPlannerROS:
    acc_lim_x: 2.5
    #acc_lim_theta: 3.2
    max_vel_x: 0.6 #0.6室内    
    min_vel_x: 0.0
    max_vel_theta: 1.3  #iias 1.0 #1.7
    min_vel_theta: -1.3 #iias -1.0 #-1.7
    min_in_place_vel_theta: 0.3
    holonomic_robot: false
    yaw_goal_tolerance: 0.5
    xy_goal_tolerance: 0.4
    #pdist_scale: 0.8 #iias
    pdist_scale: 0.4
    gdist_scale: 0.8
    occdist_scale: 0.14 #0.1 0.07
    escape_vel: 0.0
    meter_scoring: true
