# move_base common parameters
# + 2021 Tsudanuma Challenge
# + 2021 Tsukuba Challenge
# Configuration by NaokiTakahashi12
#footprint: [[-0.6, -0.2775], [-0.6, 0.2775], [0.6, 0.2775], [0.6, -0.2775]]
footprint: [[-0.2, -0.2775], [-0.2, 0.2775], [0.6, 0.2775], [0.6, -0.2775]]
