# move_base common parameters
# + 2021 Tsudanuma Challenge
# + 2021 Tsukuba Challenge
# Configuration by NaokiTakahashi12
shutdown_costmaps: false
base_global_planner: global_planner/GlobalPlanner
planner_frequency: 0.5
oscillation_distance: 0.1
oscillation_timeout: 10.0
#base_local_planner: base_local_planner/TrajectoryPlannerROS
base_local_planner: dwa_local_planner/DWAPlannerROS
controller_frequency: 9.502222
planner_patience: 1.088888
controller_patience: 1.022222
max_planning_retries: 1
